# Generated by Django 5.0.6 on 2024-07-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubirN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('pNombre', models.CharField(max_length=50)),
                ('pApellido', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('seleccion', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='core/img')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
